# Generated by Django 3.1 on 2021-09-08 02:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 9, 2, 34, 57, 565050, tzinfo=utc), verbose_name='date end'),
        ),
    ]
