# Generated by Django 3.1 on 2021-09-07 14:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 14, 8, 6, 343627, tzinfo=utc), verbose_name='date end'),
        ),
    ]
